package com.qualitesoft.freightclub.appcommon;

public class Messages {
	
	public static String forgot_password_confirmation_success = "Please check your email to reset your password.";

	public static String custom_quote_requested_admin = "== == == Custom Order has submitted a custom order quote request == *Order Details:* * OrderID:*{orderID} * Customer Name:*Custom Order AutoCom90001 address line1, address line 2, LOS ANGELES, CA, 90001 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 AutoCom10011 address line 1, address line 2, NEW YORK, NY, 10011 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 Test1234 FC Team, please review and update the quote. Freight Club - Copyright 2019 ?© Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";
	
	public static String custom_quote_requested_user = "== == == Hello, Thank you for submitting a Custom Quote. This is a confirmation that we will begin to work on processing this request. A quote will be submitted to you within 1-2 business days for review. A follow-up email will be sent to you once a quote is available. Important information to review while our team works on gathering the best quote for you: - UPSC Capital is not included in a Custom Quote and cannot be added. Additional insurance can be purchased directly from the carrier - Bill of Lading and Labels will be provided once your order has been booked and payment has been submitted If you have questions or would like to chat with a representative to discuss alternate options please contact our support team. Thanks again for choosing Freight Club and have a great day! Kind Regards, Customer Support 1-844-819-2187 info@freightclub.com <mailto:info@freightclub.com> == Freight Club - Copyright 2019 ?© Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";
	
	public static String custom_quote_requested_carrier = "== == == Custom Order has submitted a custom order quote request == *Order Details:* * OrderID:*{orderID} *Customer Name:* Custom Order | 8153 *Shipment Details:* Handling UnitsTotal WeightConditionDeclared ValueFull Truckload70 lbsNew$1000 *Shipment Information* Test1234 Test1234 *Pick-up Details: * AutoCom90001 address line1, address line 2, LOS ANGELES, CA, 90001 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789* Drop-off Details: * AutoCom10011 address line 1, address line 2, NEW YORK, NY, 10011 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 *Additional Information:* *Custom Order Details* [X] Driver required for loading & unloading [ ] Regulated items that require further inspection [ ] Prohibited or restricted items [ ] Dangerous or hazardous goods [ ] Requires refrigeration *Regulatory Details.* Test1234 Freight Club - Copyright 2019 ?© Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";
	
	public static String custom_quote_requested_carrier_stg = "== == == Custom Order has submitted a custom order quote request == *Order Details:* * OrderID:*{orderID} *Customer Name:* Custom Order | 10834 *Shipment Details:* Handling UnitsTotal WeightConditionDeclared ValueFull Truckload70 lbsNew$1000 *Shipment Information* Test1234 Test1234 *Pick-up Details: * AutoCom90001 address line1, address line 2, LOS ANGELES, CA, 90001 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789* Drop-off Details: * AutoCom10011 address line 1, address line 2, NEW YORK, NY, 10011 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 *Additional Information:* *Custom Order Details* [X] Driver required for loading & unloading [ ] Regulated items that require further inspection [ ] Prohibited or restricted items [ ] Dangerous or hazardous goods [ ] Requires refrigeration *Regulatory Details.* Test1234 Freight Club - Copyright 2019 ?© Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";
	
	public static String custom_quote_requested_full_truckload_carrier = "== == == Custom Order has submitted a custom order quote request == *Order Details:* * OrderID:*{orderID} *Customer Name:* Custom Order | 8153 *Shipment Details:* Handling UnitsTotal WeightConditionDeclared ValueFull Truckload70 lbsNew$1000 *Shipment Information* Test1234 Test1234 *Pick-up Details: * AutoCom90001 address line1, address line 2, LOS ANGELES, CA, 90001 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789* Drop-off Details: * AutoCom10011 address line 1, address line 2, NEW YORK, NY, 10011 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 *Additional Information:* *Custom Order Details* [X] Driver required for loading & unloading [ ] Regulated items that require further inspection [ ] Prohibited or restricted items [ ] Dangerous or hazardous goods [ ] Requires refrigeration *Regulatory Details.* Test1234 Freight Club - Copyright 2019 ?© Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";
	
	public static String order_ready_for_booking = "The Freight Club team has reviewed your custom order request {orderID} and has provided a quote. Review the order and proceed with the booking through the Manage Orders - Open Quotes page. *Order Details:* * OrderID:*{orderID} * PO Number:*{poNumber} AutoCom90001 address line1, address line 2, LOS ANGELES, CA, 90001 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 AutoCom10011 address line 1, address line 2, NEW YORK, NY, 10011 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 {regulatoryDetails} Thanks again for choosing Freight Club and have a great day! Kind Regards, Customer Support 1-844-819-2187 info@freightclub.com <mailto:info@freightclub.com> Freight Club - Copyright 2019 ?© Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";
	
	public static String order_confirmation_mail_user = "Thank you for submitting your order, this is a confirmation of your booking. *Order Details:* * OrderID:*{orderID} *Customer Name:* Custom Order * Carrier Name:* Estes Express Lines *Carrier QuoteID: *102 *Shipment Details* Handling UnitsTotal WeightConditionDeclared ValueFull Truckload70 lbsNew$1000 *Shipment Information* Test4321 *Custom Order Details* [X] Driver required for loading & unloading [ ] Regulated items that require further inspection [ ] Prohibited or restricted items [ ] Dangerous or hazardous goods [ ] Requires refrigeration *Regulatory Details.* Test4321 AutoCom90001 address line1, address line 2, LOS ANGELES, CA, 90001 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 AutoCom10011 address line 1, address line 2, NEW YORK, NY, 10011 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 Test4321 Please note that labels and bills of lading for custom orders are not available through the application. We will be reaching out to you with a carrier bill of lading to use with your shipment. If you have questions or would like to chat with a representative to discuss alternate options please contact our support team. Thanks again for choosing Freight Club and have a great day! Kind Regards, Customer Support 1-844-819-2187 info@freightclub.com <mailto:info@freightclub.com>";
		
	public static String order_confirmation_mail_user1 = "Thank you for submitting your order, this is a confirmation of your booking. *Order Details:* * OrderID:*{orderID} *Customer Name:* Custom Order * Carrier Name:* FC Test Carrier *Carrier QuoteID: *222 *Shipment Details* Handling UnitsTotal WeightConditionDeclared ValueBags70 lbsNew$1000 *Shipment Information* Test4321 *Custom Order Details* [ ] Driver required for loading & unloading [X] Regulated items that require further inspection [ ] Prohibited or restricted items [ ] Dangerous or hazardous goods [ ] Requires refrigeration *Regulatory Details.* Test4321 AutoCom90001 address line1, address line 2, LOS ANGELES, CA, 90001 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 AutoCom10011 address line 1, address line 2, NEW YORK, NY, 10011 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 Test4321 Please note that labels and bills of lading for custom orders are not available through the application. We will be reaching out to you with a carrier bill of lading to use with your shipment. If you have questions or would like to chat with a representative to discuss alternate options please contact our support team. Thanks again for choosing Freight Club and have a great day! Kind Regards, Customer Support 1-844-819-2187 info@freightclub.com <mailto:info@freightclub.com>";
	
	public static String order_confirmation_mail_user_ltl = "Thank you for submitting your order, this is a confirmation of your booking. *Order Details:* * OrderID:*{orderID} *Customer Name:* Custom Order * Carrier Name:* FC Test Carrier *Carrier QuoteID: *222 *Shipment Details* Package TypeQuantityWeightDimensionsCategoryConditionDeclared ValueFreight ClassProduct170 lbs11x12x13 insSafe/VaultNew$40050Box1251 lbs65x40x40 insSafe/VaultNew$100200Pallet1251 lbs65x40x40 insSafe/VaultNew$100200 *Shipment Information* Test4321 *Custom Order Details* [X] Driver required for loading & unloading [ ] Regulated items that require further inspection [ ] Prohibited or restricted items [ ] Dangerous or hazardous goods [ ] Requires refrigeration *Regulatory Details.* Test4321 AutoCom90001 address line1, address line 2, LOS ANGELES, CA, 90001 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 AutoCom10011 address line 1, address line 2, NEW YORK, NY, 10011 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 Test4321 Please note that labels and bills of lading for custom orders are not available through the application. We will be reaching out to you with a carrier bill of lading to use with your shipment. If you have questions or would like to chat with a representative to discuss alternate options please contact our support team. Thanks again for choosing Freight Club and have a great day! Kind Regards, Customer Support 1-844-819-2187 info@freightclub.com <mailto:info@freightclub.com>";

	public static String order_confirmation_mail_admin = "Custom Order has submitted a booked the following custom order: *Order Details:* * OrderID:* {orderID} * Customer Name: *Custom Order * Carrier Name: *Estes Express Lines * Carrier QuoteID: *102 *Shipment Detail*: Handling UnitsTotal WeightConditionDeclared ValueFull Truckload70 lbsNew$1000 *Shipment Information* Test4321 *Custom Order Details* [X] Driver required for loading & unloading [ ] Regulated items that require further inspection [ ] Prohibited or restricted items [ ] Dangerous or hazardous goods [ ] Requires refrigeration *Regulatory Details.* Test4321 AutoCom90001 address line1, address line 2, LOS ANGELES, CA, 90001 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 AutoCom10011 address line 1, address line 2, NEW YORK, NY, 10011 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 Test4321 Please contact the carrier to complete the booking, and update the waybill and tracking information in the order details. Freight Club - Copyright 2019 ?© Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";
	
	public static String order_confirmation_mail_admin1 = "Custom Order has submitted a booked the following custom order: *Order Details:* * OrderID:* {orderID} * Customer Name: *Custom Order * Carrier Name: *FC Test Carrier * Carrier QuoteID: *222 *Shipment Detail*: Handling UnitsTotal WeightConditionDeclared ValueBags70 lbsNew$1000 *Shipment Information* Test4321 *Custom Order Details* [ ] Driver required for loading & unloading [X] Regulated items that require further inspection [ ] Prohibited or restricted items [ ] Dangerous or hazardous goods [ ] Requires refrigeration *Regulatory Details.* Test4321 AutoCom90001 address line1, address line 2, LOS ANGELES, CA, 90001 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 AutoCom10011 address line 1, address line 2, NEW YORK, NY, 10011 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 Test4321 Please contact the carrier to complete the booking, and update the waybill and tracking information in the order details. Freight Club - Copyright 2019 ?© Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";

	public static String custom_order_cannot_be_fulfilled = "Unfortunately, we were unable to find a carrier who was able to fulfill your custom order request. *Order Details:* * OrderID:*{orderID} * Customer Name:*Custom Order * Purchase Order:*DIR_C03 AutoCom90001 address line1, address line 2, LOS ANGELES, CA, 90001 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 AutoCom10011 address line 1, address line 2, NEW YORK, NY, 10011 9:00 AM - 4:00 PM first name last name a@gmail.com 0123456789 Test1234 If you have questions or would like to chat with a representative to discuss alternate options please contact our support team. Kind Regards, Customer Support 1-844-819-2187 info@freightclub.com <mailto:info@freightclub.com> Freight Club - Copyright 2019 ?© Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";
		
	public static String sent_to_carrier = "Hi, Thank you for submitting the dispute details. We have submitted it to the carrier for an update. Please allow 7-14 business days for a response. We will provide an update when a carrier response is received. Thanks, Freight Club Claims";
		
	public static String residential_reroute_requested_customer = "Test1 Test Automation Test Automation first name last name {orderID} {wayBill} {poNumber} {carrierName} Test Location 90001 US CA LOS ANGELES Residential #123, Los Angeles Yes Yes";
		
	public static String commercial_reroute_requested_customer = "Test1 Test Automation Test Automation first name last name {orderID} {wayBill} {poNumber} {carrierName} Test Location 2 35004 US AL MOODY Commercial #123, Moody 12:00 PM 4:00 PM Yes Yes";

	public static String amazon_reroute_requested_customer = "Test1 Test Automation Test Automation first name last name {orderID} {wayBill} {poNumber} {carrierName} Test Location 3 90001 US CA LOS ANGELES Amazon FBA Warehouse #321, Los Angeles Yes Yes";

	public static String residential_reroute_requested_carrier = "Hello {carrierName}, Please confirm if you can reroute the below order to the new location that has been provided. Also please include a quote for any additional cost that may occur. Do let us know if there are any issues. = Reroute Request = *Company: *Test Automation *Consignee Name*:* first name last name *OrderID: *{orderID} *Waybill:* {wayBill} *Customer PO Number:* {poNumber} *Carrier:* {carrierName} * Requested Reroute Information: *Consignee Name: first name last name Location Name: Test Location Address: #123, Los Angeles LOS ANGELES, CA, US, 90001 Drop-Off Times: - Delivery Appointment: Yes Limited Access: Yes Sincerely, The Freight Club TeamFreight Club - Copyright 2019 © Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";
				
	public static String commercial_reroute_requested_carrier = "Hello {carrierName}, Please confirm if you can reroute the below order to the new location that has been provided. Also please include a quote for any additional cost that may occur. Do let us know if there are any issues. = Reroute Request = *Company: *Test Automation *Consignee Name*:* first name last name *OrderID: *{orderID} *Waybill:* {wayBill} *Customer PO Number:* {poNumber} *Carrier:* {carrierName} * Requested Reroute Information: *Consignee Name: first name last name Location Name: Test Location 2 Address: #123, Moody MOODY, AL, US, 35004 Drop-Off Times: 12:00 PM - 4:00 PM Delivery Appointment: Yes Limited Access: Yes Sincerely, The Freight Club TeamFreight Club - Copyright 2019 © Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";
		
	public static String amazon_reroute_requested_carrier = "Hello {carrierName}, Please confirm if you can reroute the below order to the new location that has been provided. Also please include a quote for any additional cost that may occur. Do let us know if there are any issues. = Reroute Request = *Company: *Test Automation *Consignee Name*:* first name last name *OrderID: *{orderID} *Waybill:* {wayBill} *Customer PO Number:* {poNumber} *Carrier:* {carrierName} * Requested Reroute Information: *Consignee Name: first name last name Location Name: Test Location 3 Address: #321, Los Angeles LOS ANGELES, CA, US, 90001 Drop-Off Times: - Delivery Appointment: Yes Limited Access: Yes Sincerely, The Freight Club TeamFreight Club - Copyright 2019 © Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";

	public static String residential_reroute_approved_customer = "Test 3 Freight Club first name last name first name last name {orderID} {wayBill} {poNumber} {carrierName} Test Location 90001 US CA LOS ANGELES Residential #123, Los Angeles Yes Yes";
	
	public static String commercial_reroute_approved_customer = "Test 3 Freight Club first name last name first name last name {orderID} {wayBill} {poNumber} {carrierName} Test Location 2 35004 US AL MOODY Commercial #123, Moody 12:00 PM 4:00 PM Yes Yes";

	public static String amazon_reroute_approved_customer = "Test 3 Freight Club first name last name first name last name {orderID} {wayBill} {poNumber} {carrierName} Test Location 3 90001 US CA LOS ANGELES Amazon FBA Warehouse #321, Los Angeles Yes Yes";

	public static String residential_reroute_approved_carrier = "Test4 Freight Club first name last name first name last name {orderID} {wayBill} {poNumber} {carrierName} Test Location 90001 US CA LOS ANGELES Residential #123, Los Angeles Yes Yes";
	
	public static String commercial_reroute_approved_carrier = "Test4 Freight Club first name last name first name last name {orderID} {wayBill} {poNumber} {carrierName} Test Location 2 35004 US AL MOODY Commercial #123, Moody 12:00 PM 4:00 PM Yes Yes";

	public static String amazon_reroute_approved_carrier = "Test4 Freight Club first name last name first name last name {orderID} {wayBill} {poNumber} {carrierName} Test Location 3 90001 US CA LOS ANGELES Amazon FBA Warehouse #321, Los Angeles Yes Yes";

	public static String reroute_request_decline_customer = "Hello Freight Club, *The* reroute you requested has been denied and is unable to be processed. *This is because of the following reason: Incorrect address reroute denied reason If you have any concerns, please contact us immediately by phone at 1-844-819-2187 = Denied Reroute Request = *Company: *Freight Club *Consignee Name*:* first name last name *OrderID: *{orderID} *Waybill:* {wayBill} *Customer PO Number:* {poNumber} *Carrier:* {carrierName} * Requested Reroute Information: *Consignee Name: first name last name Location Name: Test Location Address: #123, Los Angeles LOS ANGELES, CA, US, 90001 Residential Delivery Appointment: Yes Limited Access: Yes Sincerely, The Freight Club Team Freight Club - Copyright 2019 © Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";
	
	public static String email_customer_claim_initiated = "*IMPORTANT NOTE: The initiated status is not a status monitored by the claims team. You must submit your claim for review, once all documentation has been uploaded.* Thank you for initiating your claim; Intent to claim has now been successfully sent to the carrier. In order to fully submit your claim, you must upload all of the required documentation through your Manage Claims tab in your Freight Club account within 30 days of the delivery or refusal. Once you have uploaded your documents in your claim tab hit Submit for Review. *IMPORTANT NOTE: Due to the high volume of claims, we encourage you to NOT submit your claim for review until you have the replacement invoice or proof of refund. Submitting your claim prior to uploading the proof of liability will lead to delays in your claim being filed. If the replacement is on backorder, you may upload a replacement confirmation as long as there is a cost.* Once the Freight Club claims team receives all of your claim documentation, you will either receive an email notification confirming the successful submission of your claim, or you will be notified that there are additional pending documents required to complete the submission. Once your claim is successfully submitted to the carrier, you can expect an average adjudication time of 30 - 45 days for shipments with UPS Capital Additional insurance coverage, or 60-120 days for claims filed directly with the transportation carrier. *Please note that due to peak season volumes claim adjudication may be slightly delayed.* As a reminder, the documentation required to proceed with your damage claim are as follows: - Original Invoice - Photos of the item and packaging (if the freight was refused/not delivered, set the \"location\" of the freight to 'carrier' to bypass the requirement) - Proof of liability (Refund, Replacement, Repair or Credit) If any other documents you have are not listed above, please add those documents to the additional documents area. Should you have any questions, please reach out to claims@freightclub.com for assistance. Thank you, Freight Club Claims Team Freight Club - Copyright 2019 © Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";
	
	public static String email_customer_claim_initiated_loss = "*IMPORTANT NOTE: The initiated status is not a status monitored by the claims team. You must submit your claim for review, once all documentation has been uploaded.* Thank you for initiating your claim; Intent to claim has now been successfully sent to the carrier. In order to fully submit your claim, you must submit all of the required documentation through your Manage Claims tab in your Freight Club account within 30 days of the confirmation of loss. Once you have uploaded your documents in your claim tab hit Submit for Review. *IMPORTANT NOTE: Due to the high volume of claims, we encourage you to NOT submit your claim for review until you have the replacement invoice or proof of refund. Submitting your claim prior to uploading the proof of liability will lead to delays in your claim being filed. If the replacement is on backorder, you may upload a replacement confirmation as long as there is a cost.* Once the Freight Club claims team receives all of your claim documentation, you will either receive an email notification confirming the successful submission of your claim, or you will be notified that there are additional pending documents required to complete the submission. Once your claim is successfully submitted to the carrier, you can expect an average adjudication time of 30 - 45 days for shipments with UPS Capital Additional insurance coverage, or 60 - 120 days for claims filed directly with the transportation carrier. *Please note that due to peak season volumes claim adjudication may be slightly delayed.* As a reminder, the documentation required to proceed with your loss claim is as follows: - Commercial or Sales Invoice - Signed Bill of lading - Proof of liability (Refund, Replacement, Repair or Credit) If any other documents you have are not listed above, please add those documents to the additional documents area. Should you have any other questions, please reach out to claims@freightclub.com for assistance. Thank you, Freight Club Claims Team Freight Club - Copyright 2019 © Freight Club 12020 Sunrise Valley Dr. # 100 Reston, Virginia, 20191 You are receiving this email because you are a customer of Freight Club Terms & Conditions <https://www.freightclub.com/terms-and-conditions>; | Privacy Policy <https://app.freightclub.com/Home/PrivacyPolicy>;";

	public static String email_carrier_claim_initiated = "We have been advised that the above {trackingID} was reported Damage. Please provide a copy of the signed Proof of Delivery and the freight invoice to claims@freightclub.com for review. *Additional Reference Information:* Waybill: {wayBill} Consignee: Test DropOffFirstName Test DropOffLastName Test DropOffAddressLine1 NEW YORK, NY 10011 1234567890 Please consider this our intent to claim. Proof of value and all other documentation will be provided with our formal claim submission, as soon as the documentation is available. Our insurance carrier, UPS Capital, will be in contact with you once this claim is filed. Thank you, Freight Club Claims Team";
	
	public static String email_carrier_claim_initiated_loss = "We have been advised that the above {trackingID} was reported Loss. Please provide a copy of the signed Proof of Delivery and the freight invoice to claims@freightclub.com for review. *Additional Reference Information:* Waybill: {wayBill} Consignee: Test DropOffFirstName Test DropOffLastName Test DropOffAddressLine1 NEW YORK, NY 10011 1234567890 Please consider this our intent to claim. Proof of value and all other documentation will be provided with our formal claim submission, as soon as the documentation is available. Thank you, Freight Club Claims Team";

	public static String email_communication_user = "{claimType} Claim Initiated Order ID: {orderID} / PO: {customerPO} was sent to {email}";
	
	public static String email_communication_carrier = "Intent to claim Order ID: {orderID} / Tracking Number {trackingID} was sent to {email}";
	
	public static String email_customer_additional_docs_needed = "We have reviewed your claim and determined that additional documentation is required prior to filing. Please upload the following documents to your claim in your Manage Claims tab in your Freight Club account. Sales Invoice, Pictures, Proof of liability, Addiotional documents Should you have any questions or require additional assistance please contact us at claims@freightclub.com Thank you, Freight Club Claims Team";
	
	public static String email_customer_pending_documentation = "We have reviewed your claim and determined that additional documentation is required prior to filing. Please upload the following documents to your claim in your Manage Claims tab in your Freight Club account. Others Should you have any questions or require additional assistance please contact us at claims@freightclub.com Thank you, Freight Club Claims Team";
	
	public static String email_customer_filed = "Your claim has now been successfully filed. The average adjudication time for claims with UPS Capital Additional insurance coverage purchased is 30 - 45 days or 45 - 120 days for claims filed directly with the transportation carrier. *Please note that due to peak season volumes claim adjudication may be slightly delayed.* Should any additional documents be requested from the Carrier/UPSC our claims team will reach out to you via email. You can check your claim status online through your Freight Club account under Manage Claims. You can also export all of your claim data via CSV through the same portal. Any claims in approved statuses will be submitted for payment to you within one week of the approval. Thank you, Freight Club Claims Team";
}
